version: '3'

services:
    go-app:
        image: golang:1.22.3-alpine
        container_name: go-app
        volumes:
            - ./:/app
        depends_on:
            - carepet-scylla1
        working_dir: /app
        command: sh -c "
            go build ./cmd/migrate &&
            go build ./cmd/sensor &&
            go build ./cmd/loadtest &&
            go build ./cmd/server &&
            tail -F anything
            "
        expose:
            - '8000'
    carepet-scylla1:
        image: scylladb/scylla
        container_name: carepet-scylla1
        command: ['--smp=1', '--memory=1GB', '--overprovisioned=1', '--developer-mode=1']
        ports:
            - '9042:9042'
        environment:
            - 'SCYLLA_JMX_ADDR=-ja 0.0.0.0'
            - 'SCYLLA_JMX_REMOTE=-r'
        expose:
            - '7199'

    carepet-scylla2:
        image: scylladb/scylla
        container_name: carepet-scylla2
        command: ['--smp=1', '--memory=1GB', '--overprovisioned=1', '--developer-mode=1', "--seeds=carepet-scylla1"]
        ports:
            - '9043:9042'
        environment:
            - 'SCYLLA_JMX_ADDR=-ja 0.0.0.0'
            - 'SCYLLA_JMX_REMOTE=-r'
        expose:
            - '7199'

    carepet-scylla3:
        image: scylladb/scylla
        container_name: carepet-scylla3
        command: ['--smp=1', '--memory=1GB', '--overprovisioned=1', '--developer-mode=1', "--seeds=carepet-scylla1"]
        ports:
            - '9044:9042'
        environment:
            - 'SCYLLA_JMX_ADDR=-ja 0.0.0.0'
            - 'SCYLLA_JMX_REMOTE=-r'
        expose:
            - '7199'
